services:
  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - /opt/proxy/data:/data
      - /opt/proxy/letsencrypt:/etc/letsencrypt
    networks:
      - nginx
      - proxy_external
      - proxy_proxy_internal
    depends_on:
      - proxy_db

  proxy_db:
    image: mariadb:10.11
    container_name: proxy_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: npm
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: npm
    volumes:
      - /opt/proxy/mysql:/var/lib/mysql
    networks:
      - proxy_proxy_internal

networks:
  nginx:
    name: nginx
    driver: bridge
  proxy_external:
    name: proxy_external
    driver: bridge
  proxy_proxy_internal:
    name: proxy_proxy_internal
    internal: true
