networks:
  nginx:
    name: nginx
    external: true
  monitor_internal:
    name: monitor_internal
    internal: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - /srv/uptime-kuma:/app/data
    networks:
      - nginx
      - monitor_internal
    ports:
      - "3001:3001"

  kuma-db:
    image: mariadb:11
    container_name: kuma-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: kuma
      MYSQL_DATABASE: kuma
      MYSQL_USER: kuma
      MYSQL_PASSWORD: kuma
    volumes:
      - /opt/kuma:/var/lib/mysql
    networks:
      - monitor_internal
